version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      build:
        steps:
          - checkout
          - run: cd client
          - run:
              command: npm start
              background: true
          - run: sleep 5
          - run: npm run test